### ISSUE TITLE
Question: Can I use the GameMaker HTML5 Runtime for free?

### ISSUE THREAD

**Issue by yjgaia** [YoYoGames/GameMaker-HTML5#511] opened 2024-06-16 11:45 UTC
Hello YoYoGames,

I recently learned that the GameMaker HTML5 Runtime has been open-sourced. First and foremost, I respect your decision and, as a developer, I want to express my gratitude.

As a long-time fan of GameMaker, I am curious if it is permissible to create a separate exporter based on the GameMaker HTML5 Runtime. I understand that GameMaker applies a paid license for commercial games, but I am wondering if creating a separate exporter based on this open-source runtime also falls under this license.

Thank you.

**Comment by stuckie** [comment] 2024-06-17 13:05
Hello.

Technically, this is not a bug nor feature request so would I be able to get you to go through the Help Desk for this?
Please see https://contact.gamemaker.io/contact-us and *in this specific case* choose Account, then Other Issue.
Ensure you reply to the email about ticket creation as well, and reference this GitHub ticket.

This will ensure the right people see it!
I'll close this ticket now as there isn't anything that we can do here.

Thanks.

**Closed as not planned by stuckie** 2024-06-17 13:05 UTC
