### ISSUE TITLE
instance_deactivate_object no longer works

### ISSUE THREAD

**Issue by NastyWizard** [YoYoGames/GameMaker-HTML5#134] opened 2023-02-06 19:10 UTC
worked fine before updating to latest release, I was a few updates behind so not sure exactly when this started.

![image](https://user-images.githubusercontent.com/39597982/217062918-1cfd60d8-4306-4833-b047-ff252ab41cbb.png)

**Comment by NastyWizard** [comment] 2023-02-06 19:57
I tested it in a new project and it works fine, this is only happening in my game, this is the block in the generated html where its complaining

`function(_D3,_74)
{
	var _xw1=true;
	if(_S3)
	{
		var _S23=_D3;
		if(_S23!=_L62)_S23|=_74;
		var _E8=_Ft2++;
		var _Kk=_S3._yN._Kk;
		for(var index=_Kk.length-1;
index>=0;index--)
		{
			var _Gt=_Kk[index];
			if(!_Gt.marked&&(_Gt._Ht2<=_E8))
			{
				var _1F=_Gt._1F;
				if(_1F._It2[_S23])
				{
					_xw1=_Gt._b6(_D3,_74,_Gt,_Gt);
				}
			}
		}
	}
	return _xw1;
}`

**Comment by NastyWizard** [comment] 2023-02-07 00:18
I tested it in a new project and it works fine, this is only happening in my game, this is the block in the generated js where its complaining
```
{
	var _xw1=true;
	if(_S3)
	{
		var _S23=_D3;
		if(_S23!=_L62)_S23|=_74;
		var _E8=_Ft2++;
		var _Kk=_S3._yN._Kk;
		for(var index=_Kk.length-1;
index>=0;index--)
		{
			var _Gt=_Kk[index];
			if(!_Gt.marked&&(_Gt._Ht2<=_E8))
			{
				var _1F=_Gt._1F;
				if(_1F._It2[_S23])
				{
					_xw1=_Gt._b6(_D3,_74,_Gt,_Gt);
				}
			}
		}
	}
	return _xw1;
}```

**Comment by Grisgram** [comment] 2023-02-07 16:23
I had this marked error also some time ago... unfortunately i can not remember exactly what the reason was, but it was on my side.

the error says "reading undefined" - so maybe the object is in a state where it no longer is marked for... deleting or deactivating - and the marked flag is no longer available.
Can it be, that you deactivate it more than once in the same frame? something like a destroy event and a manual deactivate call? i think, this "marked" is a flag telling gm smth like "marked for..." "deletion" or "deactivation" - maybe you call it on an object already marked or so during the frame.

**Comment by DiasFranciscoA** [comment] 2023-05-04 11:04
Hello @NastyWizard. This bug couldn't be reproduced, please provide a project containing this problem so we can investigate further.

NOTE: This is probably fixed already.

**Comment by stuckie** [comment] 2024-05-16 08:43
Closing as above.

**Closed as not planned by stuckie** 2024-05-16 08:43 UTC
Labels: gms2-bug
